### ISSUE TITLE
Replies shoud not include anonaddy header.

### ISSUE THREAD

**Issue by yurividal** [anonaddy/anonaddy#300] opened 2022-06-14 06:08 UTC
Whenever i reply to a message that has been forwarded to me by anonaddy, the receipeint sees the anonaddy header. Example:

````
------- Original Message -------
On Tuesday, June 14th, 2022 at 6:57 AM, xxx wrote:


This email was sent to testing@xxx.zzz from aaa@bbb.com and has been forwarded by AnonAddy
Click here to deactivate this alias 
````

This part should automatically be removed by anonaddy

**Comment by W3LLD0NE** [comment] 2022-06-16 03:59
Just to remind that as a workaround you can disable this header completely until it's implemented (you have to be a paid customer though).

**Comment by willbrowningme** [comment] 2022-06-16 08:41
As @W3LLD0NE mentioned you can turn off this banner completely in the settings. I will see if I can remove it automatically although it may be tricky to make sure regex or text matching always works 100% exactly as expected.

**Comment by yurividal** [comment] 2022-06-16 08:46
You could just use the auto-generated line and have everything above it removed. Its like some other services do it. (Example: Webex, has a clear "Do not change anything bellow this line" part in the auto-generated emails for meetings, exactly for that reason. The system them dumps everything above (or bellow, idk) that "marker". Its just a suggestion. 
I have turned off the banner, but it's a nice-to-have feature to think about, and improve this amazing product even more

**Comment by willbrowningme** [comment] 2022-08-03 15:57
Closing this as it is a duplicate of [#253](https://github.com/anonaddy/anonaddy/issues/253).

**Closed by willbrowningme** 2022-08-03 15:57 UTC
