### ISSUE TITLE
Feature Request]  Smtp credentials and server

### ISSUE THREAD

**Issue by Gottarocket** [anonaddy/anonaddy#232] opened 2021-11-29 09:11 UTC
Yes , I know anonaddy is a email forwarder service and not a email service technically but main selling point which I love is alias which hides my original email address. So when I use other selfhosted dockers containers which asks for smtp details to send 2fa or confirmation or even notification about docker status I would like to hide my smtp credentials and email address from there too . Yes its selfhosted so no issue adding my own email smtp details whose server I have control over but it would tie me to said email service with my remote selfhosted service  So would appreciate a workaround feature to fill smtp details without selfhosting anonaddy or atleast for paid customers . Other alias provider was considering adding similar request on its roadmap so I felt this can work so I am adding this as a request as I dont have or found alternatives yet to hide original email smtp and address on server

**Comment by Coderdude112** [comment] 2021-11-30 02:57
Duplicate of #184. There is a guide that the creator of Anonaddy gave me, haven't gotten around to looking into it until now.

Was actually on my way to find the article when I came across your post lol

**Comment by Gottarocket** [comment] 2021-11-30 03:48
Its not on roadmap too I believe . Sure will find alternatives as Selfhosting email is kinda messy

**Closed** 2021-11-30 03:49 UTC
