### ISSUE TITLE
Search is broken in Firefox extension

### ISSUE THREAD

**Issue by cmbail** [anonaddy/anonaddy#514] opened 2023-08-29 20:53 UTC
Steps to replicate:
Search for a term in FIrefox toolbar or sidebar.

Expected result:
One alias shown (as in app.addy.io - screenshot below)

Actual result:
1800 matches shown (correct match is not even visible) screenshot:
![Screenshot 2023-08-29 at 1 51 47 PM](https://github.com/anonaddy/anonaddy/assets/3613239/167d94d6-2d3e-4f29-a349-d4eb5a1b7498)

![Screenshot 2023-08-29 at 1 53 09 PM](https://github.com/anonaddy/anonaddy/assets/3613239/f3f0ef8e-f793-4755-a34c-96bb84508473)

This seems to have started with a recent update. Search was working a few days ago.

**Comment by willbrowningme** [comment] 2023-08-30 06:31
Thanks, duplicate of https://github.com/anonaddy/browser-extension/issues/44, I've just fixed this in v2.2.5 of the extension that should be live shortly.

**Closed by willbrowningme** 2023-08-30 06:31 UTC

**Comment by cmbail** [comment] 2023-08-30 16:49
Thanks! I searched on "search" but presumably didn't find it because it was already closed.
