### ISSUE TITLE
Can't verify email signatures sent through aliases

### ISSUE THREAD

**Issue by xyhhx** [anonaddy/anonaddy#590] opened 2024-02-06 00:57 UTC
I'm using a self-hosted instance and have enabled PGP encryption. I'm using Thunderbird to read the emails, but it show the signature as invalid because the key's UID doesn't match the `From:` header.

![Screenshot_2024-02-05_19-55-57](https://github.com/anonaddy/anonaddy/assets/105510262/99297c42-cd8c-472b-b647-81dda27ee3b9)

**Comment by willbrowningme** [comment] 2024-02-06 10:06
Duplicate of #164. I'm afraid at the moment I don't know of any workable solution to this.

Since you're self-hosting you can manually add your alias addresses as identities to your signing key if you want to get rid of that message.

**Closed by willbrowningme** 2024-02-06 10:06 UTC

**Comment by xyhhx** [comment] 2024-02-06 13:59
> Since you're self-hosting you can manually add your alias addresses as identities to your signing key if you want to get rid of that message.

That's unrealistic, since I have well over 100 aliases.
