### ISSUE TITLE
Unable to turn off 2FA

### ISSUE THREAD

**Issue by WA8IQO** [anonaddy/anonaddy#189] opened 2021-08-23 22:09 UTC
I'm a new user of Anonaddy and I'm dumping Authy 2FA for another provider (Aegis) after the initial set up. In order to do so, I have to "Disable" the current 2FA settings and re-establish them.

I've attempted to disable 2 factor authentication on two different accounts with the same result. When I enter the current password it tells me "Current Password Incorrect" even tho it is correct. 

I assume it is the account password. I also tried the 2FA code just in case. Neither worked. Am I missing something or is this a bug?

**Comment by willbrowningme** [comment] 2021-08-24 07:45
That's correct, you need to enter your account's password in order to disable 2FA.

Have you tried resetting your account password and then trying again?

I cannot reproduce this and all tests relating to it are passing.

**Comment by WA8IQO** [comment] 2021-08-24 20:06
I attempted to reset the password as you suggested. I got "Incorrect Password Entered" response. But now, I will be locked out of the account once I log out. I allowed the process to updated my password manager and I don't know what the old password was. I also tried to just delete the account I also got "Incorrect Password Entered".

I've used two different desktops computers both with the same results. The specs on both are as follows:

Computer #1 
Linux Mint 19.3 Cinnamon
Firefox 90.0 with all installed extensions disabled and;
Chromium Version 92.0.4515.159 – no add-ons installed.

Computer #2
Windows 10 Pro
Firefox 91.0.2 with all extensions disabled and;
Chromium Version 93.0.4526.0 - no add-ons installed.

I was able to remove the recipient email address I was using and replaced it with a junk one so I can move it to a new account. At this point I think I will have to abandon the account and just create a new one.

**Comment by willbrowningme** [comment] 2021-08-25 07:48
It sounds to me that like you just have the incorrect password which is why you are not able to do any of the actions which require password confirmation.

Please try the following:

1. Use a different browser that is not logged in to AnonAddy and visit - https://app.anonaddy.com/password/reset
2. Enter your username and you will receive a reset password link
3. Choose a new password
4. Log in and use this new password to disable 2FA

The above steps assume you still have access to the current 2FA codes.

**Comment by willbrowningme** [comment] 2021-08-25 14:56
Closing this as I do not believe it is a bug. Please send me an email if you are still having issues.

**Closed by willbrowningme** 2021-08-25 14:56 UTC
