### ISSUE TITLE
Use a different Sender Name for each Alias?

### ISSUE THREAD

**Issue by martin-braun** [anonaddy/anonaddy#475] opened 2023-06-23 07:20 UTC
It would be nice if I could change my Sender Name for each alias. For instance, I want to share my real name only with entities I trust. I still don't trust such entities enough to give them my real email address for good reasons.

**Comment by willbrowningme** [comment] 2023-06-23 07:31
This is a duplicate of #279 and has already been added to the [roadmap](https://github.com/anonaddy/anonaddy/projects/1#card-79830989).

**Closed by willbrowningme** 2023-06-23 07:31 UTC

**Comment by martin-braun** [comment] 2023-06-23 08:01
@willbrowningme How did I miss that ... thanks for the prompt response.
