### ISSUE TITLE
Error when sending from alias

### ISSUE THREAD

**Issue by blimeybloke** [anonaddy/anonaddy#310] opened 2022-06-26 01:25 UTC
I have pretty much everything working quite well.  The one issue I am running into is when I try to send from the alias in the portal.  It says, open email client, which for me is gmail.

I then do a test email to my fastmail account and it fails with the following error:

`Attempted Reply/Send Failed
An attempt to send or reply from your alias xr70s9xj@mydomain.com was just made from myemail@gmail.com which failed because it didn't pass authentication checks and could be a spoofed.

In order to send or reply from an alias there must be a valid DMARC policy present for gmail.com and your message must be permitted by that DMARC policy.

The attempt was trying to send the message to the following destination: myemail@fastmail.com

If this attempt was made by yourself, then you need to make sure your recipient's domain (gmail.com) has the correct DNS records in place; SPF, DKIM and DMARC.

If this attempt was not made by you, then someone else may be attempting to send a message from your alias. Make sure you have a suitable DMARC policy in place (with p=quarantine or p=reject) along with SPF and DKIM records to protect your recipient's email address from being spoofed.`

**Comment by willbrowningme** [comment] 2022-06-26 10:45
Please could you [forward me that email](https://anonaddy.com/contact/) and I'll look into this for you.

**Comment by blimeybloke** [comment] 2022-06-26 13:29
Will - I am sorry, I should have add that this is self hosted.

**Comment by willbrowningme** [comment] 2022-06-27 07:45
Did you make sure to include the correct `/etc/rspamd/local.d/milter_headers.conf` config mentioned in the self-hosting instructions Rspamd section?

**Comment by blimeybloke** [comment] 2022-06-27 15:48
Yes, I copy/pasted exactly what the self host guide mentioned.

**Comment by blimeybloke** [comment] 2022-06-27 23:34
also attaching my dmarc.  It has " " 
I have tried it without the " " not sure if it matters but this is my dmarc
![dmarc](https://user-images.githubusercontent.com/20652035/176054055-515f4988-38fb-42f1-b1d0-6c0532866c09.png)

**Comment by blimeybloke** [comment] 2022-06-28 02:05
Here is the mail log.  Maybe this will help.  I sent a test email from a generic yahoo account I had to the alias.  It worked and was sent to my gmail account.

What you see in the log is me hitting reply to the email in my gmail account, going to that generic yahoo account (from the alias)

The last part of the log is it sending me the email I posted 2 posts ago that the reply failed.

![log](https://user-images.githubusercontent.com/20652035/176074356-bbfbb46e-2604-4946-9271-345bab105e4d.png)

cheers

**Comment by blimeybloke** [comment] 2022-06-28 13:08
Yep, just tried using another recipient that was not gmail and same issue.
I do see 
` CAC083E656: milter-reject: END-OF-MESSAGE from sonic301-48.consmr.mail.gq1.yahoo.com[98.137.64.174]: 4.7.1 Try again later; from=<second@yahoo.com> to=<5x4qx5sw+newsender=outlook.com@mydomain.net> proto=ESMTP helo=<sonic301-48.consmr.mail.gq1.yahoo.com>`

I am using the exact code from the self host guide:

`# Milter configuration
milter_default_action = accept
milter_protocol = 6
smtpd_milters = inet:localhost:11332
non_smtpd_milters = $smtpd_milters
milter_mail_macros =  i {mail_addr} {client_addr} {client_name} {auth_authen}
`

and /etc/rspamd/local.d/milter_headers.conf is also identical to the guide

thanks

**Comment by blimeybloke** [comment] 2022-06-28 13:56
a complete rebuild seems to be my answer :(

**Comment by willbrowningme** [comment] 2022-06-28 14:02
Hmm that milter-reject message looks like greylisting to me, do you have the greylisting module enabled in Rspamd?

The only way that "Attempted Reply/Send" notification can be triggered is [here](https://github.com/anonaddy/anonaddy/blob/master/app/Console/Commands/ReceiveEmail.php#L150=) in the code. So either Rspamd is not adding the `X-AnonAddy-Dmarc-Allow` header as it should, or it has added the `X-AnonAddy-Spam` header.

If you run `sudo rspamadm configdump -m` is the `milter_headers` module enabled?

If you run the following on your local computer `ssh -L 11334:localhost:11334 johndoe@0.0.0.0` where johndoe@0.0.0.0 is the user and IP that you use to ssh normally into the server.

Then visit http://localhost:11334/#history in your browser and attempt to send from an alias, then click on the incoming message on that page and see if it has the `DMARC_POLICY_ALLOW` symbol.

**Comment by blimeybloke** [comment] 2022-06-28 14:11
Thanks Will, I appreciate the response.  Here are modules:
Modules enabled: spf, history_redis, maillist, rbl, bayes_expiry, mime_types, whitelist, dkim_signing, forged_recipients, arc, regexp, emails, once_received, phishing, greylist, settings, mid, multimap, hfilter, dkim, force_actions, dmarc, milter_headers

I did catch this error:
mail postfix/cleanup[1898]: warning: milter inet:localhost:11332: can't read SMFIC_BODYEOB reply packet header: Connection timed out

Doing some google searches on that one lol

**Comment by blimeybloke** [comment] 2022-06-28 14:45
hah! ok so an update.  It does work now.  However, I went to the other side of extreme and now I get 2 emails for every 1 I send.

Still seeing this in the mail.log : postfix/cleanup[2083]: warning: milter inet:localhost:11332: can't read SMFIC_BODYEOB reply packet header: Connection timed out

I wonder if that is why its sending dupe emails?

**Comment by willbrowningme** [comment] 2022-06-28 15:01
If you run `sudo service rspamd status` is Rspamd active and running without any errors?

**Comment by blimeybloke** [comment] 2022-06-28 15:09
`root@mail:~# service rspamd status
● rspamd.service - rapid spam filtering system
     Loaded: loaded (/lib/systemd/system/rspamd.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-06-28 10:30:09 EDT; 38min ago
       Docs: https://rspamd.com/doc/
   Main PID: 632 (rspamd)
      Tasks: 5 (limit: 4556)
     Memory: 143.5M
     CGroup: /system.slice/rspamd.service
             ├─632 rspamd: main process; 0.1 msg/sec, 0.0 msg/sec spam, 0.1 msg/sec ham; 1.16s avg processing time
             ├─947 rspamd: rspamd_proxy process (localhost:11332)
             ├─948 rspamd: controller process (localhost:11334)
             ├─949 rspamd: normal process (localhost:11333)
             └─950 rspamd: hs_helper process

Jun 28 10:30:09 mail systemd[1]: Started rapid spam filtering system.
Jun 28 10:30:10 mail rspamd[632]: 2022-06-28 10:30:10 #632(main) <73ba5b>; main; main: rspamd 3.2 is loading configuration, build id: release`

this is what I see

**Comment by blimeybloke** [comment] 2022-06-28 15:23
I may have fixed this.  I will update this in about 30-60 once I run some tests.  I originally disabled ipv6 on the server.  I was running tests without it and then forgot to re-enable.  So far it looks like the milter error is gone.  I figured this out by searching google and someone on a google group posted that it could be a dns issue.  A light clicked and I asked myself "I wonder if it is trying to do ipv6?"  reenabled and then rebooted.  

So far the tests are working as it should, but I want to do more before I say all clear.

**Comment by willbrowningme** [comment] 2022-07-01 08:08
I hope you've resolved this now, I'm closing this as it doesn't appear to be an issue with AnonAddy.

**Closed by willbrowningme** 2022-07-01 08:08 UTC

**Comment by spyesx** [comment] 2022-11-04 14:06
Hi guys, I'm receiving the same email from my self-hosted instance.

>Attempted Reply/Send Failed
>
>An attempt to send or reply from your alias [...]

I just upgraded to the last docker image with Rspamd, I send emails from gmail to anonaddy in order to reply to an email received earlier. As far as I know, gmail has a proper dmarc record.

`/etc/rspamd/local.d/milter_headers.conf` is present in the container and looks correct.

`rspamadm configdump -m` result is:

```
Modules enabled: force_actions, forged_recipients, phishing, milter_headers, regexp, mime_types, once_received, history_redis, settings, arc, maillist, fuzzy_check, dkim_signing, dkim, whitelist, spf, rbl, dmarc, mid, multimap, greylist, hfilter, bayes_expiry, emails
Modules disabled (explicitly): metadata_exporter, neural, ratelimit, rspamd_update, spamtrap, aws_s3, dcc, asn, external_relay, bimi, replies, p0f, trie, http_headers, mx_check, chartable
Modules disabled (unconfigured): antivirus, fuzzy_check, elastic, url_redirector, reputation, clickhouse, spamassassin, metric_exporter, clustering, ip_score, dynamic_conf, maps_stats, fuzzy_collect, external_services
Modules disabled (no Redis):
Modules disabled (experimental):
Modules disabled (failed):
```

is there anything I can provide to help?

**Comment by spyesx** [comment] 2022-11-06 12:03
Hi there! IPv6 looks to be involved. Although IPv6 is not the problem.

As said in https://github.com/anonaddy/docker/issues/192#issuecomment-1304784209

>Alright, there is a big problem with something inside this container. My eyes are turned to Rspamd but I couldn't test it.
>
>After enabling IPv6 for Docker, suddenly we can send emails through Anonaddy.
>
>What does it mean?
>
>Well, it means that something in the container is using IPv6 only where it shouldn't.
>
>- Is there an IPv6 hardcoded somewhere?
>- Is there a bad implementation of DNS queries somewhere? Ex: By getting the first IP of a resolver (not standard) instead of a round robin (standard).
>
>This is a important issue because yes, we should use IPv6 today but, we should not have IPv6 only.

If it was the case for Docker then it will be the case for a normal host.

@blimeybloke I think this issue should be reopen until it's fixed.

**Comment by klibansky** [comment] 2022-11-23 10:27
FYI, I have the same problem and it turned out to be setting the correct SPF DNS record.
https://github.com/anonaddy/docker/issues/192#issuecomment-1324838216

**Comment by Zegorax** [comment] 2023-04-21 20:33
Hello everyone,

If you are using Docker containers, I found the root cause of this issue. You can read more details here : https://github.com/anonaddy/docker/issues/192#issuecomment-1518111988

There is a temporary fix while waiting for my PR to be merged.
