### ISSUE TITLE
[BUG] with the setting "Update Display From Format"

### ISSUE THREAD

**Issue by drum3870** [anonaddy/anonaddy#642] opened 2024-05-19 08:48 UTC
While having pgp encryption on, "No Name - just the alias" value for the "Update Display From Format" setting doesn't seem to work properly. Mail received display `alias+sender=example.com@anonaddy.com` in the from field instead of `alias@anonaddy.com`, revealing the original sender in the target inbox. This is an issue for users who want to hide the original sender from their mail provider as this information may be equally as sensitive as the subject or content of the e-mail.

note for the devs : Thank you for your work and your amazing product !

**Comment by willbrowningme** [comment] 2024-05-20 05:25
You can enabled the `Use Reply-To Header For Replying` setting which will set the `From:` header as the alias `alias@anonaddy.com` but then set the `Reply-To:` header as `alias+sender=example.com@anonaddy.com`.

At the moment there is no way to completely hide the sender of the email as this would break the reply functionality.

A fix for this is currently on the roadmap - [https://github.com/anonaddy/anonaddy/projects/1#card-87274322](https://github.com/anonaddy/anonaddy/projects/1#card-87274322).

 A similar issue is also open here - [https://github.com/anonaddy/anonaddy/issues/608](https://github.com/anonaddy/anonaddy/issues/608).

**Comment by willbrowningme** [comment] 2024-06-26 10:52
Closing as duplicate of #608, this is still on the roadmap.

**Closed by willbrowningme** 2024-06-26 10:52 UTC
