### ISSUE TITLE
Unique use case with unalias email address with to:/cc: to other email addresses

### ISSUE THREAD

**Issue by cb3inco** [anonaddy/anonaddy#185] opened 2021-08-13 16:48 UTC
I have a unique use case that I'm not sure that Anonaddy could solve. Let me explain.

Our company has a domain that we've use for internal communication only. We don't want users emailing services like gmail, yahoo, etc. Say this domain is example.com. 

If we allowed users to use anonaddy with a domain of our choosing, a user could email external to our email system with send/receive using domain.net. However the problem is if a user (Sam) has an email thread going on with say bob@ gmailuser.com and now wants to add jim@ example.com, this exposes jim@ example.com to bob@ gmailuser.com. Is there anyway anonaddy could strip or replace that internal domain with a address for jim while keeping the thread intact for everyone? Ideally this would be nice at a system level rule (all example.com domains are aliased).

sam@ example.com <-> AnonAddy - samo@ domain.com <-> bob@ gmailuser.com is ok.

sam@ example.com <-> Anonaddy - samo@ domain.com <-> bob@ gmailuser.com is bad.
jim@ example.com                             cc: jim@ example.com <-> bob@ gmailuser.com again, is bad. 

I see something in issue #131 about rules...is this something that could address this? It would be also great if **jim** who was also a user of anonaddy could generate a alias in his account, to use a random alias from his account on this multiple recipient email.

It's rather complicated and would love to see this, but if this is not possible, then I understand. Just thought I would ask. :)

**Comment by cb3inco** [comment] 2021-08-30 03:35
Hi @willbrowningme - sorry for the confusion on this. 

Example 1:
``` from: sam@ example.com <-> AnonAddy - samo@ domain.com <-> to: bob@ gmailuser.com is ok. ```

This is the assumed normal email flow with Anonaddy in place between one person and one recipient. 

Example 2:
``` 
from: sam@ example.com <-> Anonaddy - samo@ domain.com <-> to: bob@ gmailuser.com is bad.
cc: jim@ example.com.
```
This is a email with a cc user on example.com - his true email address is exposed to bob, which sam's email is 'masked' by AnonAddy. 

I want to know if it's possible to also mask Jim's email so that when bob@ gmailuser.com replies all, both sam and jim get the response and their emails are 'masked' through Anonaddy.

Please let me know if I can further clarify this.

**Comment by willbrowningme** [comment] 2021-09-06 09:34
This seems like a duplicate of #123. At the moment CC is not supported but I will continue to investigate ways to add support for it in the situation you describe above.

**Closed by willbrowningme** 2021-09-06 09:34 UTC
