### ISSUE TITLE
Can't add recipent with .io domain

### ISSUE THREAD

**Issue by Doonga** [anonaddy/anonaddy#326] opened 2022-08-19 18:47 UTC
My real email address is on a .io domain, when i try to add that as a recipient I get an error. I'm assuming that is filtered out? I tried adding a .org email that I also have and that worked fine.

**Comment by willbrowningme** [comment] 2022-08-23 07:43
Please [send me an email](https://anonaddy.com/contact/) and let me know what the .io email is so I can check what the issue is for you.

**Comment by willbrowningme** [comment] 2022-08-30 08:27
Closing this for now as I do not believe it is an issue with AnonAddy.

**Closed by willbrowningme** 2022-08-30 08:27 UTC
